library(Seurat)
library(SCENIC)
library(AUCell)
library(RcisTarget)
library(GENIE3)
library(SCopeLoomR)
library(ggplot2)
library(foreach)

exprMat = GetAssayData(scRNAsub, layer = "counts") 
genesKept <- geneFiltering(as.matrix(exprMat),scenicOptions=scenicOptions)
exprMat_filtered <- exprMat[genesKept,]
data(list="motifAnnotations_hgnc_v9", package="RcisTarget")
motifAnnotations_hgnc <- motifAnnotations_hgnc_v9
tf_names <- getDbTfs(scenicOptions )
tf_names <- CaseMatch(search=tf_names, match = rownames(scRNAsub))
arb.algo <- import("arboreto.algo") 
adjacencies <- arb.algo$grnboost2(as.data.frame(t(as.matrix(exprMat_filtered))),tf_names=tf_names,seed=123L)
colnames(adjacencies) <- c("TF", "Target", "weight" ) 
runCorrelation(as.matrix(exprMat_filtered), scenicOptions)
runSCENIC_1_coexNetwork2modules(scenicOptions)
runSCENIC_2_createRegulons(scenicOptions, coexMethod = "top10perTarget")
scenicOptions <- initializeScenic(org="hgnc", dbDir= "cisTarget_databases",nCores=1) 
runSCENIC_3_scoreCells(scenicOptions,log2(as.matrix(exprMat_filtered)+1))
regulonAUC <- readRDS("int/3.4_regulonAUC.Rds") 
regulonAUC_mat <- AUCell::getAUC(regulonAUC)
scRNAsub[["SCENIC"]] <- CreateAssayObject(counts = regulonAUC_mat) 
scenicOptions <- runSCENIC_4_aucell_binarize(scenicOptions) 
cellInfo <- data.frame(Clusters= Idents(object = scRNAsub))
regulonAUC <- readRDS("int/3.4_regulonAUC.Rds") 
regulonAUC <- regulonAUC[onlyNonDuplicatedExtended(rownames(regulonAUC)),]
regulonActivity_byClusters <- sapply(split(rownames(cellInfo),
cellInfo$Clusters),function(cells)
  rowMeans(getAUC(regulonAUC)[,cells]))
regulonActivity_byClusters_Scaled <- t(scale(t(regulonActivity_byClusters), center = T, scale=T))
ComplexHeatmap::Heatmap(regulonActivity_byClusters_Scaled, name="Regulon activity",cluster_rows=F,col=c("#4B5B95", "white", "#CD322C")) 